name: Generate Package
run-name: ${{ github.actor }} to workable demo

on: [push]

defaults:
  run:
    shell: bash

jobs:
  Paackage-Artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checking job variables
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4.1.1

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
