name: Generate Package
run-name: CI/CD for Artifact

on: [push]

defaults:
  run:
    shell: bash

jobs:
  Paackage-Artifact:
    runs-on: ubuntu-latest

    env:
      CR_PAT: ${{ secrets.CR_PAT }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checking job variables
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4.1.1

      - name: Build
        run: |
          docker build -t ynab-app-artifact:latest app/
          repository_lowercase=$(echo "${{ env.GITHUB_REPOSITORY }}" | tr '[:upper:]' '[:lower:]')
          docker tag ynab-app-artifact:latest ghcr.io/$repository_lowercase/ynab-app-artifact:latest

      - name: Deploy
        run: |
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          repository_lowercase=$(echo "${{ env.GITHUB_REPOSITORY }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$repository_lowercase/ynab-app-artifact:latest
